# Generated by Django 6.0.3 on 2026-03-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uni', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
    ]
